### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by zhewang95** [abhi4ssj/relaynet_pytorch#1]
Great job! But I have a problem about the 2015_BOE_Chiu dataset, when I load the Subject_0x.mat file into matlab R2017a, all the variables are NaN. Do any one has idea about that?

**Comment by zhewang95** [comment]
Oh, turns out that not all the numbers are NaN.

**Comment by hwei-hw** [comment]
Hello！@abhi4ssj
I have some doubt in the process of data when I implement it and hope to get your reply. The dataset consists of 110 annotated SD-OCT B-scan images  obtained from 10 patients suffering from DME (11 B-scans per patient) and you split the dataset into non-overlapping subsets of 8 patients for training and held out 2 patients for testing. That's means we have 7 patients for training, 1 patient for validation and 2 patients for testing? And if yes, I don't know
whether you can tell me which 2 patients are used for testing? 
I will be very grateful if you can help me and I will cite your paper in the next work.

**Comment by ZeyuFu** [comment]
@Atomwh can I ask how did you get the gt_id.mat file?
