### ISSUE TITLE
Something wrong about the datasets 

### ISSUE THREAD

**Issue by Guoxs** [abhi4ssj/relaynet_pytorch#3]
Hello, I followed your instruction but confused about the datasets,  I downloaded the datasets from the link (http://people.duke.edu/~sf59/Chiu_BOE_2014_dataset.htm) as mentioned in the paper,  while the datasets consist of 610 annotated SD-OCT B-scan images of size 496x768  obtained from 10 patients suffering from DME (61 B-scans per patient). This is very different from the paper description, I think I had downloaded the wrong datasets, can you show the right link of the datasets download? thank you a lot!

**Comment by abhi4ssj** [comment]
Hi,
This is the right dataset. I think not all the scans are annotated. Only 11 scans per subject is annotated, in total 110 B-scans.

Best
Abhijit

**Comment by Guoxs** [comment]
That true, thank you!
