### ISSUE TITLE
All Layer Classification

### ISSUE THREAD

**Issue by simasima121** [abhi4ssj/relaynet_pytorch#5]
I've got the model working however it seems to only classify the top layer in an image (in black and white whereas paper had all layers being segmented in colour). Is this something that is being worked on? If not where can I contribute to bring this up to speed

**Comment by abhi4ssj** [comment]
Hi,

I added the visualization routine in the RunFile notebook. Some parts like the slicing statergy is not yet implemented. Any contribution is highly appreciated. :)

Best
Abhijit
