### ISSUE TITLE
No sample dataset to test input format

### ISSUE THREAD

**Issue by seanogor** [abhi4ssj/relaynet_pytorch#6]
I get the following error code when trying to run the first few lines of code offline on my machine, since there is no test data set to run he model on there. We have some SD-OCT images which we could use there if we new the correct specifications to input to the model. We plan to cite your work and employ it in a further research paper:

  File "/home/seanogor/Documents/Nandan/retinalwork/relaynet_pytorch/networks/data_utils.py", line 35, in get_imdb_data
    Data = h5py.File('datasets/Data.h5', 'r')
  File "/usr/local/lib/python3.5/dist-packages/h5py/_hl/files.py", line 312, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/usr/local/lib/python3.5/dist-packages/h5py/_hl/files.py", line 142, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = 'datasets/Data.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Comment by abhi4ssj** [comment]
Hi,

The input Data and Labels are saved as 4D Tensors as [NumData, channel, rows, cols]. You may modify the DataLoader to suit your data format.

Best
Abhijit

**Comment by seanogor** [comment]
Thank you for your quick response, I prefer to format my data to match the
code as it gives the best chance of success later in the model. I tried to
convert a jpg file, I attach the jpg and conversion script:

import numpy as np
import h5py

filename = 'AGee.jpg'
fin = open(filename, 'rb')
binary_data = fin.read()

f = h5py.File('foo.hdf5')
dt = h5py.special_dtype(vlen=np.dtype('uint8'))
dset = f.create_dataset('binary_data', (100, ), dtype=dt)

# Save data string converted as a np array
dset[0] = np.fromstring(binary_data, dtype='uint8')



I see your tensor format and want to convert to that format, could you give
some quick guidance how to do that. If I can get a model running, we plan
to compare with other healthy/diseased retinal images and run a novel
processing method we have on segmented retinal layers. We will of course
cite your work and share our results prior to publication.

Kind regards,
Sean

**Comment by abhi4ssj** [comment]
Hi Sean,

I have the trained model (which is bench-marked) at: https://github.com/abhi4ssj/ReLayNet/tree/master/RunFile

You may use this for comparisons.

Regarding preparing the dataset, refer to: https://github.com/abhi4ssj/ReLayNet

I used the same Data Structure in my PyTorch version.

Best
Abhijit

**Comment by abhi4ssj** [comment]
I hope this is resolved now.
