### ISSUE TITLE
When trying to run the solver.train() function, the following error is returned. Any idea why this is?

### ISSUE THREAD

**Issue by simasima121** [abhi4ssj/relaynet_pytorch#8]
RuntimeError: Traceback (most recent call last):
  File "/home/sim/anaconda3/envs/py3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 57, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/sim/anaconda3/envs/py3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 57, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/sim/notebooks/relaynet_pytorch/relaynet_pytorch/data_utils.py", line 23, in __getitem__
    weight = torch.from_numpy(weight)
RuntimeError: Trying to resize storage that is not resizable at /home/sim/install/pytorch/aten/src/TH/generic/THStorage.c:183

**Comment by simasima121** [comment]
I've solved this problem. The next I get is:

~/notebooks/relaynet_pytorch/relaynet_pytorch/net_api/losses.py in forward(self, output, target, weights, ignore_index)
     65             encoded_target[mask] = 0
     66         else:
---> 67             encoded_target.scatter_(1, target.unsqueeze(1), 1)
RuntimeError: invalid argument 4: Index tensor must have same size as output tensor apart from the specified dimension

Aparrently the tensor sizes are wrong. They are as follows: 
Encoded Target Shape: torch.Size([4, 6, 512, 64])
Encoded Target Type: torch.cuda.FloatTensor
Target Shape: torch.Size([4, 64, 2])
Target Unsqueeze Shape: torch.Size([4, 1, 64, 2])
Target type: torch.cuda.LongTensor

Any idea why this would be the case and how to resolve this?

thanks!

**Comment by abhi4ssj** [comment]
---> 67 encoded_target.scatter_(1, target.unsqueeze(1), 1)

This line is for converting the Ground Truth to one-hot encoding for evaluating class-wise Dice Loss. The output size should be 4x6x512x64 for an input of 4x512x64, if number of classes are 6 (including background).

Error might be in the dataLoader File. I am not sure.

**Comment by simasima121** [comment]
Have now solved this error and am instead getting a cuda 59 error. Are you able to share your hd5 files so that I can test where any difference may have occured or direct me towards fixing this? 

Thanks a lot.

**Comment by shayansiddiqui** [comment]
@simasima121 We will be introducing a new dataloader soon, which should resolve this issue

**Comment by meincv** [comment]
> Have now solved this error and am instead getting a cuda 59 error. Are you able to share your hd5 files so that I can test where any difference may have occured or direct me towards fixing this?
> 
> Thanks a lot.

Hi, could you please say how you solved `scatter` error? I have somehow the same problem. I have asked it at https://github.com/michuanhaohao/reid-strong-baseline/issues/120 and I appreciate your help.
